### PR TITLE
ci: test against python 3.11, and run codecov in a non-deprecated way

### PR DESCRIPTION
**Pull request by consideRatio**
More about the deprecation of codecov uploader in https://github.com/codecov/codecov-action.

### CODE REVIEW

**Comment by tomplus** [comment]
It hits https://github.com/tomplus/kubernetes_asyncio/issues/234

**Comment by consideRatio** [comment]
@tomplus yepp, I saw https://github.com/Martiusweb/asynctest/issues/163 now, suggesting that `asynctest` is dropped:

> I believe unittest.mock.AsyncMock in combination with pytest is probably your best bet for now.

Hmmm, I lack experience here.

**Comment by consideRatio** [comment]
Hmmm, trialing a bit and looking at the souce code, I'm not confident on how to proceed overall. `asynctest` is used in quite a few places and I'm not savvy with `patch` `mock` etc.

**Comment by tomplus** [comment]
Thanks for your kind words and your contribution :heart: 

Let's keep this PR opened, I'll fix the tests soon and then we'll merge it.

**Comment by tomplus** [comment]
@consideRatio Sorry, while I was fixing async tests, I had to upgrade codecov too. I completely forgot about your PR and I did the same job :/

**Comment by consideRatio** [comment]
Ah no worries at all! Thank you for your work on this project!!

**Pull request closed without merging**
