### PR TITLE
[feat] Watch() retries 410 errors

### PR DESCRIPTION
**Pull request by tomplus**
Fixes https://github.com/tomplus/kubernetes_asyncio/issues/136

### CODE REVIEW

**Comment by rjhuijsman** [comment]
Thanks for doing this! My team is excited to see this land - hopefully this can go into a release soon! 🙂 🙏🏻

**Comment by tomplus** [comment]
Thank you.
I'm preparing the next release, should be available in the following week.

**Comment by tomplus** [comment]
@rjhuijsman It has been released :rocket:

**Comment by ianbuss** [comment]
One quick question about the semantics of this that I'm not sure of. If the server has responded with a 410, the resource_version in the watch is no longer available server-side, so the reconnect would always fail with another 410 unless the resource_version is reset to None in the watch? `_reconnect` doesn't reset the resource_version as far as I can see. I've probably missed a subtlety here.

**Comment by tomplus** [comment]
@ianbuss Thanks for your question.

The idea is to try to reconnect only once with the latest resource_version we have. It may be enough in some situation. If it doesn't help an exception is raised and client has to handle it somehow (probably will fetch list of resources and start watching again).

You are right, that resetting version could make it works forever but we won't be aware that we lost some events. So it's better to make it explicit and raise an exception.

**Comment by ianbuss** [comment]
> @ianbuss Thanks for your question.
> 
> The idea is to try to reconnect only once with the latest resource_version we have. It may be enough in some situation. If it doesn't help an exception is raised and client has to handle it somehow (probably will fetch list of resources and start watching again).
> 
> You are right, that resetting version could make it works forever but we won't be aware that we lost some events. So it's better to make it explicit and raise an exception.

Agree that is the right call, such cases are best handled by the calling code. The PR interested me as I am developing a general go informer-like library over kubernetes-asyncio for all the core types and 410 Gone is one of the special cases I need to handle. Thanks for the response 👍

**Pull request merged**
