### PR TITLE
Reconnect watcher if server ends empty response

### LINKED ISSUE #95: Reconnect watcher if Kubernetes sends an empty response
In watch.py, `next()` is set to stop iteration if the k8s server provides an empty response (i.e. when the server timeout expires). I believe this is undesirable. 

https://github.com/tomplus/kubernetes_asyncio/blob/91b2c41eedd282d9ebc059377fb7f207e220133d/kubernetes_asyncio/watch/watch.py#L145-L150

Instead, the logic should be similar to the logic in the previous `except` block, which handles `asyncio.TimeoutError`:

https://github.com/tomplus/kubernetes_asyncio/blob/91b2c41eedd282d9ebc059377fb7f207e220133d/kubernetes_asyncio/watch/watch.py#L136-L141

From the perspective of kubernetes_asyncio, it should not matter if the client or if the server has timed out; the watcher should attempt to reconnect unless the user-specified timeout (`timeout_seconds`) has elapsed.

I believe this is how the standard Python client handles it:

https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/watch/watch.py#L141-L157

When `iter_resp_lines(resp)` returns a value which evaluates to False (e.g. the k8s api returns an empty response), iteration stops. Unless _stop has been set to True, the client will attempt to reconnect.

### PR DESCRIPTION
**Pull request by JacobHenner**
If the server sends an empty response (e.g. a server-side timeout was
exceeded), the watcher should reconnect unless the user has specified a
timeout. This is similar to the behavior in the standard Python
Kubernetes library.

Fixes #95

### CODE REVIEW

**Comment by JacobHenner** [comment]
It looks like this behavior was introduced in https://github.com/tomplus/kubernetes_asyncio/commit/61852ea42d4ec562d61cbe86d391e5de8a88e75c, as part of https://github.com/tomplus/kubernetes_asyncio/pull/22.

@olitheolix, could you clarify why the asyncio watcher should stop if the server has responded with an empty response? From my perspective, it seems like it'd be better if the watcher remained connected (reconnect) unless the user had specified a timeout. I just want to be sure I'm not missing something...

I notice that three test cases are failing - I'll address these as soon as I understand the above.

**Comment by olitheolix** [comment]
@JacobHenner From what I can remember, it was about the separation of concerns. The function should only deal with the current event stream and return once K8s closed that stream. The caller can then implement the desired retry/reconnect/whatever logic itself. That, at least, is how I did it In my personal version of the `Watcher`  :)

In other words, no, I do not think you are missing anything here.

**Comment by tomplus** [comment]
I'd like to keep this client similar to the official client as possible. Are we sure that empty line means that server is disconnected? I don't see such checks in the official client.

**Comment by JacobHenner** [comment]
> The function should only deal with the current event stream and return once K8s closed that stream. The caller can then implement the desired retry/reconnect/whatever logic itself.

Ah, I see. From my perspective, the library should be responsible for maintaining the connection unless a user-specified timeout has elapsed or the server has responded with some sort of error condition. I've seen other comments that lead me to believe this is the expected behavior from a client - https://github.com/kubernetes/kubernetes/issues/6513#issuecomment-90721269, for example.



> Are we sure that empty line means that server is disconnected?

It looks like it could mean a few things - https://github.com/kubernetes/kubernetes/blob/79e1ad2f4bbd05b1e56b7b57b63b2c1d67b90156/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go#L212-L261

- Timeout expired
- Marked "done"
- Error encountered

> I don't see such checks in the official client.

In the official Python client:

https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/watch/watch.py#L141-L157

When iter_resp_lines(resp) returns a value which evaluates to False (e.g. the k8s api returns an empty response), iteration stops. Unless _stop has been set to True, the client will attempt to reconnect.

**Comment by tomplus** [comment]
I got it, the official client "ignore" empty lines. In my opinion it's better if a library does mandatory retries to simplify end-client's code.

**Comment by JacobHenner** [comment]
> I got it, the official client "ignore" empty lines. In my opinion it's better if a library does mandatory retries to simplify end-client's code.

Should I adjust the tests accordingly?

**Comment by tomplus** [comment]
Yes, It'd be great.

**Comment by Junnplus** [comment]
Is there any progress on this PR?

**Comment by tomplus** [comment]
It's been solved in the latest version v30.3.0.

**Pull request closed without merging**
